project_name: flog

builds:
  - binary: flog
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - Update README.md
    - Merge pull request
    - Merge branch

archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
    - LICENSE
    - README.md

release:
  github:
    owner: mingrammer
    name: flog
  name_template: '{{.Tag}}'

brew:
  name: flog
  github:
    owner: mingrammer
    name: homebrew-flog
  commit_author:
    name: mingrammer
    email: mingrammer@gmail.com
  homepage: https://github.com/mingrammer/flog
  description: "A fake log generator for common log formats"
  install: bin.install "flog"
